Make sure preparation times printed fully and nicely
IBM/unitxt pull request #1046
Opened 2024-07-23 07:18 UTC by elronbandel

2024-07-23 07:30 UTC, elronbandel commented
Relevant for: https://github.com/IBM/unitxt/issues/1042

2024-07-23 13:47 UTC, yoavkatz approved these changes

2024-07-23 13:49 UTC, yoavkatz requested changes
The output seems a bit odd:

[Unitxt|CRITICAL|text_utils.py:122] 2024-07-23 07:47:16,556 >> 
/cards/reuters21578.py (str):
    1.0:31.579201698303223
/cards/arena_hard/response_assessment/pairwise_comparative_rating/both_games_gpt4_judge.py (str):
    1.0:22.37667727470398
/cards/clinc_oos.py (str):
    1.0:2.7218029499053955
/cards/sst2.py (str):
    1.0:19.03265643119812
/cards/arena_hard/response_assessment/pairwise_comparative_rating/first_game_only_gpt4_judge.py (str):
    1.0:15.7068612575531
/

2024-07-23 21:25 UTC, elronbandel commented
Any better now @yoavkatz ?

2024-07-28 08:57 UTC, yoavkatz approved these changes

2024-07-28 09:37 UTC, merged