A swifty PR suggested for issue #1331
IBM/unitxt pull request #1337
Opened 2024-11-10 09:19 UTC by dafnapension

closes: https://github.com/IBM/unitxt/issues/1331

Added a test to identify cases of more than one prepare file generating the same catalog file.
Consistency test works in granularity of prepare-files (can not identify two or more generations of same catalog file, within same prepare file; only across different prepare-files). But for now, and because typically, not too many `add_to_catalog` within same prepare_file, and hence can be manually tested for uniqueness, this PR may suffice.

2024-11-11 09:04 UTC, elronbandel requested changes

2024-11-11 09:04 UTC, elronbandel commented on prepare/processors/processors.py
> -add_to_catalog(
Why did you delete these?

2024-11-11 09:05 UTC, elronbandel commented on prepare/processors/processors.py
> -add_to_catalog(
I mean where are they added somewhere else? in the same file?

2024-11-11 11:19 UTC, dafnapension commented
Here is an excerpt from `processors.py` of current `main` branch, please notice the line numbers and contents:

![image](https://github.com/user-attachments/assets/0d0df742-69e6-4519-978f-1350295a090e)

Now please notice the excerpt from same file of same branch, different lines, immediately following the previous ones, but same contents:

![image](https://github.com/user-attachments/assets/e9b7c466-e907-4b58-9f7a-e0a75f9608de)

Someone pasted twice by mistake, and I removed once.

2024-11-11 11:23 UTC, dafnapension commented
On this occasion, 'while the hood is open', I added a test to catelog-consistency, to verify that not two prepare-files generate the same catalog entry (overwriting each other).  There is still no test to catch errors like the one triggered this PR: overwriting in within same prepare-file, because the automatic test works in granularity of whole prepare files.
I commented that errors like this one (that triggered this PR) can be caught (evidently, not too obviously..) by the eye..

2024-11-12 10:20 UTC, elronbandel approved these changes

2024-11-12 11:38 UTC, merged