Switch scigen card to use CrossProviderInferenceEngine
IBM/unitxt pull request #1412
Opened 2024-12-04 05:31 UTC by yifanmai

This creates a new metric `llama_3_70b_instruct_cross_provider_template_table2text_single_turn_with_reference` which is the cross provider version of `llama_3_70b_instruct_ibm_genai_template_table2text_single_turn_with_reference`, and then switches scigen to use the new metric. This allows running scigen with other model providers.

2024-12-04 05:43 UTC, yifanmai commented
Test failures seem to be due to `huggingface-cli login --token` failing and doesn't seem related to this PR.

2024-12-04 10:40 UTC, yoavkatz commented on prepare/metrics/llm_as_judge/rating/llama_3_cross_provider_table2text_template.py
> +format = "formats.llama3_instruct"
I think you should use "formats.chat_api" like in

https://www.unitxt.ai/en/latest/catalog/catalog.metrics.llm_as_judge.rating.llama_3_70b_instruct.generic_single_turn.html

2024-12-04 10:43 UTC, yoavkatz requested changes
One suggested  change.  

Also, can you commit the PR as a branch and not a fork? (Not sure yet how to approved workflows on forks to access secrets)

2024-12-04 10:44 UTC, yoavkatz commented on prepare/metrics/llm_as_judge/rating/llama_3_cross_provider_table2text_template.py
> +format = "formats.llama3_instruct"
Otherwise the formatted prompt will be nested in the user message.  [ We are going to generate an error on this in the future]

2024-12-05 06:08 UTC, closed without merging

2024-12-05 06:08 UTC, yifanmai commented
Closing this for now because I'll make the changes to @ShirApp's branch first and test there.

Also, I'm not able to create branches in this repository because I don't have write access.

2024-12-05 08:43 UTC, yoavkatz commented
Hi. @yifanmai .  I gave you write access, so you can create branches now.

2024-12-05 16:58 UTC, yifanmai commented
Thanks @yoavkatz!