Accuracy all
IBM/unitxt pull request #268
Opened 2023-11-02 10:48 UTC by naamaz

2023-11-02 12:12 UTC, yoavkatz requested changes

2023-11-02 12:25 UTC, naamaz commented on src/unitxt/metrics.py
> +        return {"accuracy": float(prediction.lower() in reference)}
Done

2023-11-02 15:56 UTC, matanor approved these changes
LGTM

2023-11-02 15:56 UTC, matanor commented on src/unitxt/metrics.py
> +        assert len(references) == 1, "Expected only one reference , but received: {references}"
```suggestion
        assert len(references) == 1, f"Expected only one reference , but received: {references}"
```

2023-11-05 11:09 UTC, yoavkatz approved these changes

2023-11-05 11:14 UTC, merged