add a card preparer for dataset xlsum
IBM/unitxt pull request #290
Opened 2023-11-08 16:26 UTC by dafnapension

2023-11-08 16:29 UTC, dafnapension commented
this script can run all the way through only after pull request 288 is merged

2023-11-12 08:47 UTC, yoavkatz commented on prepare/cards/xlsum.py
> +        test_card(card, debug=True)
set debug = False by default to speed up regressions.

2023-11-12 08:47 UTC, yoavkatz commented on prepare/cards/xlsum.py
> +        task=FormTask(
In general, we should move to a summarization task that is defined outside the card.  We can setup a meeting to discuss.

2023-11-12 08:48 UTC, yoavkatz requested changes
Changes in the comments.

2023-11-12 14:42 UTC, dafnapension commented
open  PR #301 instead, and recommitted  with signature

2023-11-12 14:42 UTC, closed without merging