example of kaggle loader
IBM/unitxt pull request #413
Opened 2023-12-19 10:22 UTC by ilyashnil

2023-12-19 11:50 UTC, elronbandel commented on src/unitxt/loaders.py
> +
```suggestion
```

This should be in the verify() function of the loader

2023-12-19 11:55 UTC, elronbandel commented on src/unitxt/loaders.py
> +        assert opendatasets_available, "Please install opendatasets in order to use the LoadFromKaggle loader (using `pip install opendatasets`) "
```suggestion
        super().verify()
        try:
            import opendatasets
        except ImportError as e:
             raise ImportError("Please install opendatasets in order to use the LoadFromKaggle loader (using `pip install opendatasets`) ") from e
```

2023-12-19 11:57 UTC, elronbandel commented on src/unitxt/loaders.py
> +        opendatasets.download(url, data_dir)
```suggestion
    def prepare(self):
        super().prepare()
        from opendatasets import download
        self.downloader = download
```

2023-12-19 11:57 UTC, elronbandel commented on src/unitxt/loaders.py
> +            self._download_from_kaggle(self.url, temp_directory)
```suggestion
            self.downloader(self.url, temp_directory)
```

2023-12-19 11:58 UTC, elronbandel requested changes
Overall looks great. Just refer to the minor changes I suggested.

2023-12-19 13:51 UTC, ilyashnil commented
1. I do not know how to make unitest without specifying credentials...
3. Where I should put the documentation?

2023-12-20 09:33 UTC, elronbandel approved these changes

2023-12-20 09:51 UTC, merged