Kendall's tau
IBM/unitxt pull request #535
Opened 2024-01-31 06:22 UTC by lilacheden

Add metric for Kendall's tau correlation coefficient

2024-02-02 05:04 UTC, lilacheden commented
Changed the metric to receive a list of floats as predictions. Casting and conversion from list[list] are done at the metric pipeline - this resolves the redundancy and coverage issues

2024-02-04 13:33 UTC, lilacheden commented on prepare/metrics/kendalltau.py
> +            field_to_field=[("references/0", "references")],
Revised the input type to avoid the redundancy in kendal's tau (see below).

2024-02-05 14:43 UTC, matanor requested changes
LGTM, was wondering about one addition, pls see my question..

2024-02-05 14:43 UTC, matanor commented on src/unitxt/metrics.py
> +            if isinstance(pred, float) and np.isnan(pred):
why was this added here?

2024-02-06 07:17 UTC, matanor approved these changes
LGTM!

2024-02-08 22:11 UTC, merged