Add filtered ffqa dataset
IBM/unitxt pull request #593
Opened 2024-02-21 14:46 UTC by marukaz

Add [WikiQA-Free_Form_QA dataset](https://huggingface.co/datasets/abacusai/WikiQA-Free_Form_QA), a long context QA dataset.
This dataset is formatted to be used in chat format, but I want to experiment with 8k context LLM, so I implemented preprocess_steps accordingly.

2024-02-21 15:27 UTC, yoavkatz commented
@elronbandel - why does the catalog preparation  this fail with:

![image](https://github.com/IBM/unitxt/assets/68273864/44d01e7b-5176-416f-9ee7-f8f1fbdd95f1)

2024-02-22 13:24 UTC, yoavkatz commented
The failure due to the fact that the this is merge from a fork.  We will handle this.

2024-02-26 13:38 UTC, elronbandel commented
Issue is now fixed @marukaz . Notice i rebased your branch to re-run the tests.

2024-02-26 16:31 UTC, elronbandel commented on prepare/cards/ffqa_filtered.py
> +    add_to_catalog(card, f"cards.ffqa_filtered.{split}")
```suggestion
add_to_catalog(card, f"cards.ffqa_filtered.{split}", overwrite=True)
```
This will help you passing the tests

2024-02-26 16:34 UTC, elronbandel commented on prepare/cards/ffqa_filtered.py
> +            ]
```suggestion
    templates="templates.qa.with_context.extractive.all"
```
The recomnded way is to add your template to the template list within `prepare/teamplates/qa` etc
This way we can build up our templates resvoir. This way your card wil be also featured in the Unitxt UI.

2024-02-26 16:35 UTC, elronbandel commented on prepare/cards/ffqa_filtered.py
> +        ),
```suggestion
       templates="templates.qa.with_context.extractive.all",
```
The recomnded way is to add your template to the template list within `prepare/teamplates/qa` etc
This way we can build up our templates resvoir. This way your card wil be also featured in the Unitxt UI.

2024-02-26 16:38 UTC, elronbandel requested changes
Really cool contribution! This dataset will be very hard to incorpirate to unitxt without the creativity you showed with the ExcuteExpression! so thank you! If you can change the things i asked it will be great. let me know when your ready and ill merge.

2024-02-28 01:32 UTC, marukaz commented
catalog preparation test is failing but when I tried `python -m unittest discover -s tests/catalog -p "test_*.py"` in my local it succeeded. I would like to rerun the test but I don't have the permission.

2024-02-28 07:09 UTC, merged