Return copied of artifacts from the artifacts cache
IBM/unitxt pull request #612
Opened 2024-02-29 14:43 UTC by matanor

This prevents any accidental changes to returned artifacts from affecting the cached objects.

2024-03-03 15:24 UTC, matanor commented
Discussion with @elronbandel 
Move the cache to include the json loaded from the file, and not the artifact itself. This is because the artifact cannot always be deepcopied (some objects within cannot be 'pickle'd)

2024-03-05 12:17 UTC, elronbandel requested changes
My only concern is that the artifact saving is reseting the cache for everyone else possible using the lru_cached_load_json. I think we should have a cache dedicated only for artifacts loading. (the fix is just to rename it to load_artifact_json_with_caching or similar

2024-03-05 12:42 UTC, matanor commented
> My only concern is that the artifact saving is reseting the cache for everyone else possible using the lru_cached_load_json. I think we should have a cache dedicated only for artifacts loading. (the fix is just to rename it to load_artifact_json_with_caching or similar

@elronbandel 
Renamed to:
```
@lru_cache(maxsize=None)
def artifacts_json_cache(artifact_path):
    return load_json(artifact_path)
```
so now the usage is:
```
    @classmethod
    def load(cls, path, artifact_identifier=None, overwrite_args=None):
        d = artifacts_json_cache(path)
        new_artifact = cls.from_dict(d, overwrite_args=overwrite_args)
        new_artifact.artifact_identifier = artifact_identifier
        return new_artifact
```
WDYT?

2024-03-05 15:05 UTC, elronbandel approved these changes

2024-03-05 15:26 UTC, merged