add intl
IBM/unitxt pull request #698
Opened 2024-03-20 22:36 UTC by pklpriv

2024-03-21 07:24 UTC, yoavkatz requested changes
Please add checks in the prepare to the new languages. Similar to this check in English.

predictions = ["hello there general kenobi", "on our way to ankh morpork"]
references = [
    ["hello there general kenobi", "hello there !"],
    ["goodbye ankh morpork", "ankh morpork"],
]
instance_targets = [
    {
        "counts": [4, 3, 2, 1],
        "totals": [4, 3, 2, 1],
        "precisions": [1.0, 1.0, 1.0, 1.0],
        "bp": 1.0,
        "sys_len": 4,
        "ref_len": 4,
        "sacrebleu": 1.0,
        "score": 1.0,
        "score_name": "sacrebleu",
    },
    {
        "counts": [2, 1, 0, 0],
        "totals": [6, 5, 4, 3],
        "precisions": [0.33, 0.20, 0.12, 0.08],
        "bp": 1.0,
        "sys_len": 6,
        "ref_len": 3,
        "sacrebleu": 0.16,
        "score": 0.16,
        "score_name": "sacrebleu",
    },
]
global_target = {
    "sacrebleu": 0.4,
    "score": 0.4,
    "counts": [6, 4, 2, 1],
    "totals": [10, 8, 6, 4],
    "precisions": [0.60, 0.50, 0.33, 0.25],
    "bp": 1.0,
    "sys_len": 10,
    "ref_len": 7,
    "score_name": "sacrebleu",
    "score_ci_low": 0.11,
    "score_ci_high": 1.0,
    "sacrebleu_ci_low": 0.11,
    "sacrebleu_ci_high": 1.0,
}
outputs = test_metric(
    metric=metric,
    predictions=predictions,
    references=references,
    instance_targets=instance_targets,
    global_target=global_target,
)

2024-03-22 12:42 UTC, pklpriv commented
> Please add checks in the prepare to the new languages. Similar to this check in English.
> 
> predictions = ["hello there general kenobi", "on our way to ankh morpork"] references = [ ["hello there general kenobi", "hello there !"], ["goodbye ankh morpork", "ankh morpork"], ] instance_targets = [ { "counts": [4, 3, 2, 1], "totals": [4, 3, 2, 1], "precisions": [1.0, 1.0, 1.0, 1.0], "bp": 1.0, "sys_len": 4, "ref_len": 4, "sacrebleu": 1.0, "score": 1.0, "score_name": "sacrebleu", }, { "counts": [2, 1, 0, 0], "totals": [6, 5, 4, 3], "precisions": [0.33, 0.20, 0.12, 0.08], "bp": 1.0, "sys_len": 6, "ref_len": 3, "sacrebleu": 0.16, "score": 0.16, "score_name": "sacrebleu", }, ] global_target = { "sacrebleu": 0.4, "score": 0.4, "counts": [6, 4, 2, 1], "totals": [10, 8, 6, 4], "precisions": [0.60, 0.50, 0.33, 0.25], "bp": 1.0, "sys_len": 10, "ref_len": 7, "score_name": "sacrebleu", "score_ci_low": 0.11, "score_ci_high": 1.0, "sacrebleu_ci_low": 0.11, "sacrebleu_ci_high": 1.0, } outputs = test_metric( metric=metric, predictions=predictions, references=references, instance_targets=instance_targets, global_target=global_target, )

@yoavkatz How do we actually create those `predictions` and `references` sentences? Is there any rule to pick those from dataset?

2024-03-24 07:09 UTC, elronbandel commented
I think they are randomly picked. Best to choose examples the reflect a real data as much as possible. Cc @yoavkatz .

2024-03-25 15:11 UTC, yoavkatz commented
Thanks.  Perhaps worth while to add another instance for each case, where the prediction=reference, to see the score is indeed 1.0?  This is done in English and Japanese.

2024-03-26 11:47 UTC, pklpriv commented
> Thanks. Perhaps worth while to add another instance for each case, where the prediction=reference, to see the score is indeed 1.0? This is done in English and Japanese.

@yoavkatz Sure, I will add them. For Japanese there is only one as well and it is opposite case - we only have test for pred=ref. I think it is worth to add such for Japanese as well.

2024-03-26 11:52 UTC, pklpriv commented
@yoavkatz @elronbandel 

To install 'ko-mecab' , MacOS users may need to install `mecab` with brew with such command:
`brew install mecab`

Only with that I had installation of `sacrebleu[ko]` successful. There could be update of some README. I could create some bash script to run with setup. Such script could check OS of user and install mecab with brew accordingly.

If we go with one of options above or something different - is not my decision to make, therefore I draft that PR until it is resolved

2024-03-26 12:34 UTC, yoavkatz commented
> @yoavkatz @elronbandel
> 
> To install 'ko-mecab' , MacOS users may need to install `mecab` with brew with such command: `brew install mecab`
> 
> Only with that I had installation of `sacrebleu[ko]` successful. To inform user about that, we could update README. I could create some bash script to run with setup. Such script could check OS of user and install mecab with brew accordingly.
> 
> If we go with one of options above or something different - is not my decision to make, therefore I draft that PR until it is resolved
 
 To be consistent with other metrics, I think the right way to do this, is that if the metric does not load, print a message with the needed installation  instructions.   Unitxt minimized installation requirements, so we don't want to require such an installation when not required.

2024-03-26 17:17 UTC, pklpriv commented
@elronbandel @yoavkatz 

I added check for libraries and additional examples for tests.

2024-03-27 11:24 UTC, yoavkatz approved these changes

2024-03-27 11:32 UTC, yoavkatz commented on src/unitxt/metrics.py
> +bre
```suggestion

```

2024-03-27 11:34 UTC, elronbandel approved these changes

2024-03-27 12:54 UTC, merged