Encode types (reciprocate parse_type) and use it to make RemoveValues indifferent to process_every_valuelues
IBM/unitxt pull request #706
Opened 2024-03-24 21:36 UTC by dafnapension

2024-03-25 03:57 UTC, dafnapension commented on src/unitxt/type_utils.py
> +
Does not work for union-s

2024-03-27 13:32 UTC, elronbandel requested changes
I would call it `infer_type` and it should return type rather than string describing the type.

2024-03-28 08:02 UTC, dafnapension commented
@elronbandel , completed the  object->`infer_type_string`, and readily added  `infer_type` as you noted.

2024-03-28 08:36 UTC, elronbandel approved these changes

2024-03-28 10:05 UTC, merged