Support for loading dictionaries
IBM/unitxt pull request #784
Opened 2024-04-25 12:07 UTC by pawelknes

Added loader which can be used to load dictionaries as per #699

2024-04-30 09:44 UTC, yoavkatz commented on src/unitxt/loaders.py
> +class LoadDirectory(Loader):
I think it should be either LoadDictionary or LoadFromConstants.

Please also add a documentation string with example of how to use it, so will be appear in the auto generated documentation.

2024-04-30 09:45 UTC, yoavkatz commented on tests/library/test_loaders.py
> +        for data_type, instances in data.items():
```suggestion
        for split, instances in data.items():
```

2024-04-30 09:48 UTC, yoavkatz commented on tests/library/test_loaders.py
> +            for instance, stream in zip(instances, streams[data_type]):
```suggestion
            for original_instance, stream_instance in zip(instances, streams[data_type]):
```

2024-04-30 09:49 UTC, yoavkatz requested changes
Thanks. Very useful class. I added a few comments.

2024-05-06 10:30 UTC, dafnapension commented on src/unitxt/loaders.py
> +        return MultiStream(
suggesting:
return MultiStream.from_iterables(self.data)

2024-05-06 11:47 UTC, pawelknes commented on src/unitxt/loaders.py
> +        return MultiStream(
Good point, thanks

2024-05-06 12:27 UTC, yoavkatz commented on tests/library/test_loaders.py
> +    def test_load_from_directory(self):
```suggestion
    def test_load_from_dictionary(self):
```

2024-05-06 12:27 UTC, yoavkatz approved these changes
Looks good thanks.

2024-05-06 13:39 UTC, merged