Code mixing metric
IBM/unitxt pull request #956
Opened 2024-06-26 18:19 UTC by arielge

- Metric that utilizes generative LLM to estimate if a text is code-mixed
- Added language identification task + example card
- Format for Starling LM

2024-06-30 17:48 UTC, elronbandel approved these changes

2024-07-01 05:36 UTC, elronbandel reviewed
@arielge @eladven @yoavkatz I think the 7b model is crashing the machine on preparation test, what would you advise?

2024-07-01 07:48 UTC, arielge commented
Probably the easiest is to not run `test_metric` if a gpu is not available. Let me see if that does the trick

2024-07-01 10:40 UTC, arielge commented
OK so this is still not enough as it looks like just loading the model crashes the test... Any ideas?

2024-07-02 10:18 UTC, elronbandel commented on src/unitxt/metrics.py
> +        )
```suggestion
        if not hasattr(self, "inference_model") or self.inference_model is None:
            self.inference_model = HFPipelineBasedInferenceEngine(
                model_name=model_id, max_new_tokens=1
            )
```

2024-07-02 10:18 UTC, elronbandel requested changes
Make sure the model is instantiated only once (see my suggestion)

2024-07-02 10:46 UTC, elronbandel commented on src/unitxt/metrics.py
> +
```suggestion
     inference_model: InferenceEngine = Field(defalut_factory=lambda:  HFPipelineBasedInferenceEngine(
            model_name="Nexusflow/Starling-LM-7B-beta", max_new_tokens=1, lazy_load=True
        )
```
Counting on https://github.com/IBM/unitxt/pull/980

2024-07-02 10:46 UTC, elronbandel reviewed
see the latest comments counting on https://github.com/IBM/unitxt/pull/980

2024-07-02 11:19 UTC, elronbandel approved these changes

2024-07-02 11:55 UTC, merged